FROM debian:latest
LABEL maintainer="Aaron Chan <zwchen037@gmail.com>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y \
    wget perl fontconfig make \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
