FROM ubuntu:latest
LABEL maintainer="Aaron Chan <zwchen037@gmail.com>"

# 设置环境变量，避免交互式安装过程中出现的提示
ENV DEBIAN_FRONTEND=noninteractive

# 安装必要的基础工具
RUN apt-get update \
  && apt-get install -y \
    git wget curl \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

CMD ["bash"]
