name: Archive

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Choose an workflow"
        required: true
        default: "docker_base_image"
  # schedule:
  #   # 每月5号14:30分开始执行（北京时间+8）
  #   - cron: "30 14 5 * *"

jobs:
  Outside:
    name: Docker Archive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pull docker images
        run: |
          docker pull chanzz0/texlive
          docker pull debian
          docker pull ubuntu
          docker pull archlinux
      - name: Push GitLab
        run: |
          docker push

  Inside:
    name: Docker Archive
    needs: Outside
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pull docker images
        run: |
          docker pull chanzz0/texlive
          docker pull debian
          docker pull ubuntu
          docker pull archlinux
      - name: Push Coding
        run: |
          docker push
      - name: Push cnb
        run: |
          docker push
