name: Pull images and Push release

on:
  push:
    branches: [main]

jobs:
  pull_images:
    name: Pull images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pull Docker images
        run: |
          docker pull
      - name: List imported images
        run: |
          docker images


